version: 2.0

defaults: &defaults
  docker:
    - image: cimg/ruby:2.7-node
  working_directory: ~/project

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - run: mkdir log
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./

  download_cc_reporter:
    <<: *defaults
    steps:
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p cc/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc/cc-test-reporter
            chmod +x ./cc/cc-test-reporter
      - persist_to_workspace:
          root: ~/project
          paths:
            - cc/cc-test-reporter

  run_bundler:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: echo "export rvm_ignore_gemsets_flag=1" >> ~/.rvmrc
      - run: sudo apt-get update && sudo apt-get install -y libsodium-dev
      - run: bundle config set --local path 'vendor/bundle'
      - run: bundle check || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/project/vendor/bundle

  run_rspec_tests:
    <<: *defaults
    docker:
      - image: cimg/ruby:2.7-node
    environment:
      RACK_ENV: "test"
      CIRCLE_ARTIFACTS: "./tmp"
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: sudo apt-get update && sudo apt-get install -y libsodium-dev
      - run: bundle config set --local path 'vendor/bundle'
      - run: bundle check
      - run: bundle exec rspec spec
      - run: ./cc/cc-test-reporter format-coverage -t simplecov -o cc/codeclimate.rspec.json tmp/coverage/.resultset.json
      - persist_to_workspace:
          root: ~/project
          paths:
            - cc/codeclimate.rspec.json

  upload_cc_coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./cc/cc-test-reporter upload-coverage -i cc/codeclimate.rspec.json

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code
      - download_cc_reporter:
          requires:
            - checkout_code
      - run_bundler:
          requires:
            - download_cc_reporter
      - run_rspec_tests:
          requires:
            - run_bundler
      - upload_cc_coverage:
          requires:
            - run_rspec_tests
